### ISSUE TITLE
Error (NPE) when issuing the access token

### ISSUE THREAD

**Issue by thiloplanz** [wso2/carbon-identity#1023] opened 2015-09-27 01:46 UTC
I get the following error when trying to exchange an OAuth2 auth code for an access token:

    Error when issuing the access token. 
    java.lang.NullPointerException
	at  org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:207)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AuthorizationCodeGrantHandler.issue(AuthorizationCodeGrantHandler.java:163)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:206)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:177)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.getAccessToken(OAuth2TokenEndpoint.java:230)

**Comment by thiloplanz** [comment] 2015-10-01 04:41
It appears that this only happens until an access token has been issued successfully using other methods. For example, I always get this error until I use "implicit grant" mode at least once. Implicit mode produces an access token, and after that "authcode" exchanges also work well (without the NPE).

**Comment by bkabele** [comment] 2015-12-29 09:39
In my oppinion this is caused by AuthorizationGrantCache(line 91, master-7e13602). Function return value is not assigned to a variable. There should be:
cacheEntry = getFromSessionStore(replaceFromCodeId(key.getUserAttributesId()));

**Comment by IndunilRathnayake** [comment] 2016-04-18 11:47
Hi,
This issue is currently fixed ( https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/17),  hence closing this entry. 
Thanks
Indunil

**Closed by IndunilRathnayake** 2016-04-18 11:47 UTC
