### ISSUE TITLE
NullPointerException when accessing OpenID user profile

### ISSUE THREAD

**Issue by thiloplanz** [wso2/carbon-identity#993] opened 2015-09-23 12:48 UTC
I get this HTTP 500 Internal Server Error with release 5.0.0 (returned as HTML, not JSON, too)

    java.lang.NullPointerException
    org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInfoJSONResponseBuilder.getUserAttributesFromCache(UserInfoJSONResponseBuilder.java:57)
    org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInfoJSONResponseBuilder.getResponseString(UserInfoJSONResponseBuilder.java:42)
    org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint.getUserClaims(OpenIDConnectUserEndpoint.java:60)

Maybe this is because the access token used belongs to the "admin" user?

**Comment by thiloplanz** [comment] 2015-09-23 13:06
> Maybe this is because the access token used belongs to the "admin" user?

It also happens with regular users.

**Comment by IndunilRathnayake** [comment] 2016-04-18 12:57
Hi,
This can't be reproduced in IS 5.1.0 or 5.0.0. Please describe your environment and the exact steps which you have followed, in order to reproduce this.
Thanks
Indunil

**Comment by johannnallathamby** [comment] 2016-05-14 18:52
Closing the issue because due to lack of information.

**Closed by johannnallathamby** 2016-05-14 18:52 UTC
